import { ITableStyle } from "./types";

export const winFontsC = [
    "Algerian",
    "Arial",
    "Bahnschrift",
    "Broadway",
    "Calibri",
    "Cambria",
    "Candara",
    "Castellar",
    "Centaur",
    "Century",
    "Chiller",
    "Consolas",
    "Constantia",
    "Corbel",
    "Courier",
    "Ebrima",
    "Elephant",
    "Fixedsys",
    "Forte",
    "Gabriola",
    "Gadugi",
    "Garamond",
    "Georgia",
    "Gigi",
    "Haettenschweiler",
    "Harrington",
    "Impact",
    "Jokerman",
    "Leelawadee",
    "Mistral",
    "Modern",
    "NSimSun",
    "Onyx",
    "Papyrus",
    "Parchment",
    "Perpetua",
    "Playbill",
    "Pristina",
    "Ravie",
    "Rockwell",
    "Roman",
    "Script",
    "SimSun",
    "Stencil",
    "Sylfaen",
    "Symbol",
    "Tahoma",
    "Terminal",
    "Verdana",
    "Webdings"
];

export const tableStyles: ITableStyle[] = [
    { id: 1, name: "Basic table", image: "table.png", colors: { header: "white", row: "white", stroke: "black", alt_row: "white", row_text: "black", alt_row_text: "black", header_text: "black" }, isActive: true },
    { id: 2, name: "Basic grey", image: "table_grey.png", colors: { header: "black", row: "grey", stroke: "white", alt_row: "#C8C8C8", row_text: "white", alt_row_text: "white", header_text: "white" }, isActive: false },
    { id: 3, name: "Basic blue", image: "table_blue.png", colors: { header: "#0082CB", row: "#B0C8E2", stroke: "white", alt_row: "#E3EDFC", row_text: "white", alt_row_text: "#243E84", header_text: "white" }, isActive: false },
    { id: 4, name: "Basic orange", image: "table_orange.png", colors: { header: "#F95E19", row: "#F9D298", stroke: "white", alt_row: "#F2E4BB", row_text: "white", alt_row_text: "#9F6B53", header_text: "white" }, isActive: false },
    { id: 5, name: "Basic green", image: "table_green.png", colors: { header: "#447A06", row: "#CADD7C", stroke: "white", alt_row: "#DEF2B3", row_text: "white", alt_row_text: "#3C5D16", header_text: "white" }, isActive: false },
    { id: 6, name: "Basic purple", image: "table_purple.png", colors: { header: "#662B8C", row: "#A69AB7", stroke: "white", alt_row: "#DBCAE8", row_text: "white", alt_row_text: "#643E7D", header_text: "white" }, isActive: false },
    { id: 7, name: "Basic brown", image: "table_brown.png", colors: { header: "#661F03", row: "#D8C29E", stroke: "white", alt_row: "#F0E5D0", row_text: "white", alt_row_text: "#9A5F48", header_text: "white" }, isActive: false },
    { id: 8, name: "Basic deep blue", image: "table_blue_2.png", colors: { header: "#0019FF", row: "#D2D8FC", stroke: "white", alt_row: "#B1C0E8", row_text: "#5760AC", alt_row_text: "white", header_text: "white" }, isActive: false },
    { id: 9, name: "Basic red", image: "table_red.png", colors: { header: "#E01414", row: "#F4BFBD", stroke: "white", alt_row: "#DD8787", row_text: "white", alt_row_text: "white", header_text: "white" }, isActive: false },
    { id: 10, name: "Basic yellow", image: "table_yellow.png", colors: { header: "#FFD60B", row: "#FCECAC", stroke: "white", alt_row: "#E5D298", row_text: "#C48A3F", alt_row_text: "white", header_text: "white" }, isActive: false },
    { id: 11, name: "Simple table", image: "table_2.png", colors: { header: "white", row: "#CCCCCC", stroke: "#666666", alt_row: "white", row_text: "white", alt_row_text: "#727272", header_text: "black" }, isActive: false },
    { id: 12, name: "Simple grey", image: "table_2_grey.png", colors: { header: "black", row: "#FFFFFF", stroke: "#000000", alt_row: "white", row_text: "black", alt_row_text: "black", header_text: "white" }, isActive: false },
    { id: 13, name: "Simple blue", image: "table_2_blue.png", colors: { header: "#EEF8FF", row: "#A2D6F9", stroke: "#0082CB", alt_row: "white", row_text: "white", alt_row_text: "#0082CB", header_text: "#0082CB" }, isActive: false },
    { id: 14, name: "Simple orange", image: "table_2_orange.png", colors: { header: "#FFFCF0", row: "#F7CFA4", stroke: "#F95E19", alt_row: "white", row_text: "white", alt_row_text: "#683C2E", header_text: "#683C2E" }, isActive: false },
    { id: 15, name: "Simple green", image: "table_2_green.png", colors: { header: "#F0FCD0", row: "white", stroke: "#447A06", alt_row: "#CADD7C", row_text: "#39462A", alt_row_text: "white", header_text: "#39462A" }, isActive: false },
    { id: 16, name: "Simple purple", image: "table_2_purple.png", colors: { header: "#F7E4F5", row: "#FFFFFF", stroke: "#662B8C", alt_row: "#DBCAE8", row_text: "#705780", alt_row_text: "white", header_text: "#705780" }, isActive: false },
    { id: 17, name: "Simple brown", image: "table_2_brown.png", colors: { header: "#F4ECE4", row: "#FFFFFF", stroke: "#661F03", alt_row: "#D8C29E", row_text: "#674F46", alt_row_text: "white", header_text: "#671C00" }, isActive: false },
    { id: 18, name: "Simple deep blue", image: "table_2_blue_2.png", colors: { header: "#0019FF", row: "#FFFFFF", stroke: "#0019FF", alt_row: "#B1C0E8", row_text: "#505BBC", alt_row_text: "white", header_text: "white" }, isActive: false },
    { id: 19, name: "Simple red", image: "table_2_red.png", colors: { header: "#FFE9F5", row: "#FFFFFF", stroke: "#E01414", alt_row: "#F4BFBD", row_text: "#754545", alt_row_text: "white", header_text: "#754545" }, isActive: false },
    { id: 20, name: "Simple yellow", image: "table_2_yellow.png", colors: { header: "#FFFFEB", row: "#FFFFFF", stroke: "#FFD60B", alt_row: "#FCECAC", row_text: "#807540", alt_row_text: "#8B7505", header_text: "#807540" }, isActive: false },
]